<?php

namespace Modules\TransactionManagement\Http\Controllers\Web\New\Admin\Report;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Service\BaseServiceInterface;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\View\View;
use Modules\TripManagement\Service\Interface\TripRequestServiceInterface;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\TripManagement\Entities\TripRequest;
use Illuminate\Support\Facades\DB;

class ReportController extends BaseController
{
    use AuthorizesRequests;
    protected $tripRequestService;

    public function __construct(TripRequestServiceInterface $tripRequestService)
    {
        parent::__construct($tripRequestService);
        $this->tripRequestService = $tripRequestService;
    }

    public function index(?Request $request, string $type = null): View|Collection|LengthAwarePaginator|null|callable|RedirectResponse
    {
        return parent::index($request, $type); // TODO: Change the autogenerated stub
    }

    public function earningReport(Request $request): View|Collection|LengthAwarePaginator
    {
        $this->authorize('transaction_view');
        $criteria = [
            'payment_status' => PAID
        ];
        if ($request->has('search')) {
            $criteria = array_merge($criteria, [
                'search' => $request->get('search')
            ]);
        }
        $whereHasRelations = [];

        // Add criteria for the `fee` relationship to filter by `cancelled_by` being either `null` or `CUSTOMER`
        $whereHasRelations['fee'] = function ($query) {
            $query->whereNull('cancelled_by')
                ->orWhere('cancelled_by', '=', 'CUSTOMER'); // Handle `null` or `CUSTOMER`
        };
        $trips = $this->tripRequestService->index(criteria: $criteria, relations: ['zone', 'fee'], whereHasRelations: $whereHasRelations, orderBy: ['created_at' => 'desc'], limit: paginationLimit(), offset: $request['page'] ?? 1);
        return view('transactionmanagement::admin.reports.earning', compact('trips'));
    }

    public function singleEarningReportexport(int|string $id)
    {
        $this->authorize('transaction_export');
        $trip = $this->tripRequestService->findOne(id: $id, relations: ['zone', 'fee']);
        return exportData($trip, 'pdf', 'transactionmanagement::admin.reports.single-earning-invoice');

    }

    public function earningReportExport(Request $request): \Illuminate\Contracts\View\View|Factory|Response|StreamedResponse|string|Application
    {
        $this->authorize('transaction_export');

        $criteria = [
            'payment_status' => PAID
        ];
        $whereHasRelations = [];

        // Add criteria for the `fee` relationship to filter by `cancelled_by` being either `null` or `CUSTOMER`
        $whereHasRelations['fee'] = function ($query) {
            $query->whereNull('cancelled_by')
                ->orWhere('cancelled_by', '=', 'CUSTOMER'); // Handle `null` or `CUSTOMER`
        };
        if ($request->has('search')) {
            $criteria = array_merge($criteria, [
                'search' => $request->get('search')
            ]);
        }
        $trips = $this->tripRequestService->index(criteria: $criteria, relations: ['zone', 'fee'],whereHasRelations: $whereHasRelations, orderBy: ['created_at' => 'desc']);
        $data = $trips->map(fn($item) => [
            'id' => $item['id'],
            'Trip ID' => $item['ref_id'],
            'Date' => date('d F Y', strtotime($item['created_at'])) . ' ' . date('h:i a', strtotime($item['created_at'])),
            'Zone' => $item['zone']?->name,
            'Trip Type' => ucwords($item['type']),
            'Total Trip Cost' => getCurrencyFormat($item['paid_fare']),
            'Admin Commission' => getCurrencyFormat($item['fee'] ? ($item['fee']->admin_commission - $item['fee']->vat_tax) : 0),
            'Tax Collected' => getCurrencyFormat($item['fee'] ? $item['fee']->vat_tax : 0),
            'Earning' => getCurrencyFormat($item['fee'] ? $item['fee']->admin_commission : 0),
        ]);
        return exportData($data, 'excel', 'null');
    }


    public function expenseReport(Request $request): View|Collection|LengthAwarePaginator
    {
        $this->authorize('transaction_view');
        $criteria = [
            'payment_status' => PAID
        ];
        $whereHasRelations = [];

        // Add criteria for the `fee` relationship to filter by `cancelled_by` being either `null` or `CUSTOMER`
        $whereHasRelations['fee'] = function ($query) {
            $query->whereNull('cancelled_by')
                ->orWhere('cancelled_by', '=', 'CUSTOMER'); // Handle `null` or `CUSTOMER`
        };
        if ($request->has('search')) {
            $criteria = array_merge($criteria, [
                'search' => $request->get('search')
            ]);
        }
        $trips = $this->tripRequestService->index(criteria: $criteria, relations: ['zone', 'fee'],whereHasRelations: $whereHasRelations, orderBy: ['created_at' => 'desc'], limit: paginationLimit(), offset: $request['page'] ?? 1);
        return view('transactionmanagement::admin.reports.expense', compact('trips'));
    }

    public function expenseReportExport(Request $request): \Illuminate\Contracts\View\View|Factory|Response|StreamedResponse|string|Application
    {
        $this->authorize('transaction_export');

        $criteria = [
            'payment_status' => PAID
        ];
        $whereHasRelations = [];

        // Add criteria for the `fee` relationship to filter by `cancelled_by` being either `null` or `CUSTOMER`
        $whereHasRelations['fee'] = function ($query) {
            $query->whereNull('cancelled_by')
                ->orWhere('cancelled_by', '=', 'CUSTOMER'); // Handle `null` or `CUSTOMER`
        };
        if ($request->has('search')) {
            $criteria = array_merge($criteria, [
                'search' => $request->get('search')
            ]);
        }
        $trips = $this->tripRequestService->index(criteria: $criteria, relations: ['zone', 'fee'],whereHasRelations: $whereHasRelations, orderBy: ['created_at' => 'desc']);
        $data = $trips->map(fn($item) => [
            'id' => $item['id'],
            'Trip ID' => $item['ref_id'],
            'Date' => date('d F Y', strtotime($item['created_at'])) . ' ' . date('h:i a', strtotime($item['created_at'])),
            'Zone' => $item['zone']?->name,
            'Trip Type' => ucwords($item['type']),
            'Total Trip Cost' => getCurrencyFormat($item['paid_fare']),
            'Coupon Amount' => getCurrencyFormat($item['coupon_amount']),
            'Discount Amount' => getCurrencyFormat($item['discount_amount']),
            'Total Expense' => getCurrencyFormat($item['discount_amount'] + $item['coupon_amount'])
        ]);
        return exportData($data, 'excel', '');
    }

    public function singleExpenseReportexport(int|string $id)
    {
        $this->authorize('transaction_export');
        $trip = $this->tripRequestService->findOne(id: $id, relations: ['zone', 'fee']);
        return exportData($trip, 'pdf', 'transactionmanagement::admin.reports.single-expense-invoice');
    }

    public function dateRideTypeWiseEarningStatistics(Request $request)
    {
        $data = $this->tripRequestService->getDateRideTypeWiseEarningStatistics($request->all());
        return response()->json($data);
    }

    public function dateZoneWiseEarningStatistics(Request $request)
    {
        $data = $this->tripRequestService->getDateZoneWiseEarningStatistics($request->all());
        return response()->json($data);
    }

    public function dateRideTypeWiseExpenseStatistics(Request $request)
    {
        $data = $this->tripRequestService->getDateRideTypeWiseExpenseStatistics($request->all());
        return response()->json($data);
    }

    public function dateZoneWiseExpenseStatistics(Request $request)
    {
        $data = $this->tripRequestService->getDateZoneWiseExpenseStatistics($request->all());
        return response()->json($data);
    }

    // =========================================================================
    // Issue #28 FIX: Streaming exports for large datasets
    // =========================================================================

    /**
     * Stream earning report export - handles large datasets without memory issues
     */
    public function earningReportExportStreamed(Request $request): StreamedResponse
    {
        $this->authorize('transaction_export');

        $search = $request->get('search');

        $queryBuilder = function () use ($search) {
            $query = TripRequest::query()
                ->with(['zone', 'fee'])
                ->where('payment_status', PAID)
                ->whereHas('fee', function ($q) {
                    $q->whereNull('cancelled_by')
                        ->orWhere('cancelled_by', 'CUSTOMER');
                })
                ->orderBy('created_at', 'desc');

            if ($search) {
                $query->where(function ($q) use ($search) {
                    $q->where('ref_id', 'like', "%{$search}%")
                        ->orWhere('id', $search);
                });
            }

            return $query;
        };

        $rowMapper = function ($item) {
            return [
                'id' => $item->id,
                'Trip ID' => $item->ref_id,
                'Date' => date('d F Y h:i a', strtotime($item->created_at)),
                'Zone' => $item->zone?->name ?? 'N/A',
                'Trip Type' => ucwords($item->type),
                'Total Trip Cost' => getCurrencyFormat($item->paid_fare),
                'Admin Commission' => getCurrencyFormat($item->fee ? ($item->fee->admin_commission - $item->fee->vat_tax) : 0),
                'Tax Collected' => getCurrencyFormat($item->fee?->vat_tax ?? 0),
                'Earning' => getCurrencyFormat($item->fee?->admin_commission ?? 0),
            ];
        };

        $format = $request->get('format', 'csv');
        return exportDataStreamed($queryBuilder, $rowMapper, $format, 'earning-report.' . $format);
    }

    /**
     * Stream expense report export - handles large datasets without memory issues
     */
    public function expenseReportExportStreamed(Request $request): StreamedResponse
    {
        $this->authorize('transaction_export');

        $search = $request->get('search');

        $queryBuilder = function () use ($search) {
            $query = TripRequest::query()
                ->with(['zone', 'fee'])
                ->where('payment_status', PAID)
                ->whereHas('fee', function ($q) {
                    $q->whereNull('cancelled_by')
                        ->orWhere('cancelled_by', 'CUSTOMER');
                })
                ->orderBy('created_at', 'desc');

            if ($search) {
                $query->where(function ($q) use ($search) {
                    $q->where('ref_id', 'like', "%{$search}%")
                        ->orWhere('id', $search);
                });
            }

            return $query;
        };

        $rowMapper = function ($item) {
            return [
                'id' => $item->id,
                'Trip ID' => $item->ref_id,
                'Date' => date('d F Y h:i a', strtotime($item->created_at)),
                'Zone' => $item->zone?->name ?? 'N/A',
                'Trip Type' => ucwords($item->type),
                'Total Trip Cost' => getCurrencyFormat($item->paid_fare),
                'Coupon Amount' => getCurrencyFormat($item->coupon_amount ?? 0),
                'Discount Amount' => getCurrencyFormat($item->discount_amount ?? 0),
                'Total Expense' => getCurrencyFormat(($item->discount_amount ?? 0) + ($item->coupon_amount ?? 0)),
            ];
        };

        $format = $request->get('format', 'csv');
        return exportDataStreamed($queryBuilder, $rowMapper, $format, 'expense-report.' . $format);
    }

    /**
     * Stream transaction report export with date range filter
     */
    public function transactionReportExportStreamed(Request $request): StreamedResponse
    {
        $this->authorize('transaction_export');

        $startDate = $request->get('start_date');
        $endDate = $request->get('end_date');
        $type = $request->get('type'); // earning, expense, or all

        $queryBuilder = function () use ($startDate, $endDate, $type) {
            $query = TripRequest::query()
                ->with(['zone', 'fee', 'customer:id,first_name,last_name', 'driver:id,first_name,last_name'])
                ->where('payment_status', PAID)
                ->orderBy('created_at', 'desc');

            if ($startDate) {
                $query->whereDate('created_at', '>=', $startDate);
            }
            if ($endDate) {
                $query->whereDate('created_at', '<=', $endDate);
            }

            return $query;
        };

        $rowMapper = function ($item) {
            return [
                'Trip ID' => $item->ref_id,
                'Date' => date('Y-m-d H:i:s', strtotime($item->created_at)),
                'Zone' => $item->zone?->name ?? 'N/A',
                'Type' => ucwords($item->type),
                'Customer' => trim(($item->customer?->first_name ?? '') . ' ' . ($item->customer?->last_name ?? '')),
                'Driver' => trim(($item->driver?->first_name ?? '') . ' ' . ($item->driver?->last_name ?? '')),
                'Fare' => $item->paid_fare,
                'Discount' => $item->discount_amount ?? 0,
                'Coupon' => $item->coupon_amount ?? 0,
                'Admin Commission' => $item->fee?->admin_commission ?? 0,
                'Tax' => $item->fee?->vat_tax ?? 0,
                'Status' => $item->current_status,
            ];
        };

        $format = $request->get('format', 'csv');
        return exportDataStreamed($queryBuilder, $rowMapper, $format, 'transaction-report.' . $format);
    }
}
